services:
  back:
    build:
      context: ./back
    container_name: menu-recommend-back
    ports:
      - "8001:8000"

  front:
    build:
      context: ./front
    container_name: menu-recommend-front
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://back:8000/recommend
    depends_on:
      - back